apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: NodePort  # Vous pouvez également utiliser LoadBalancer si vous êtes sur un cloud provider
