apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "movie_db_username"
            - name: POSTGRES_PASSWORD
              value: "movie_db_password"
            - name: POSTGRES_DB
              value: "movie_db_dev"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc







